import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '@repo/ui/styles.css';
import Link from 'next/link';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Workout Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className + ' h-full'}>
      <body className="h-full flex flex-col prose max-w-none">
        <header className="sticky top-0 z-10">
          <nav className="navbar bg-base-100 capitalize drop-shadow-lg bg-primary-content">
            <div className="font-bold text-sm sm:text-xl flex-1">workout tracker</div>
            <div className="flex-none">
              <Link className="btn btn-ghost text-xs sm:text-sm" href="/tracking">
                start tracking
              </Link>
              <Link className="btn btn-ghost text-xs sm:text-sm" href="/activity/category">
                activity categories
              </Link>
            </div>
          </nav>
        </header>
        <main className="grow container mx-auto px-4 lg:w-3/4 xl:w-2/3">{children}</main>
        <footer className="footer bg-neutral text-neutral-content p-5 sticky bottom-0">
          Footer content
        </footer>
      </body>
    </html>
  );
}
