name: Build API

on:
  push:
    branches:
      - main # Adjust to your main branch name
  pull_request:
    branches:
      - main # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Or your preferred Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Prisma Migrate Deploy
        env:
          DATABASE_URL: 'mysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@127.0.0.1:3306/workout_tracker'
        working-directory: apps/api-structure
        run: |
          npx prisma migrate deploy
          npx prisma generate

      - name: Build all packages
        run: npm run build
