name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1
        with:
          mysql-version: '8.0'
          username: 'root'
          password: ''
          database: 'my_database'

      - name: Migrations
        env:
          DATABASE_URL: 'mysql://root@localhost:3306/workout_tracker'
        run: npx prisma migrate deploy
        working-directory: apps/api-structure

      - name: Build the app
        run: npm run build

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-west-2

      # - name: Deploy to EC2
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-public-ip << 'EOF'
      #     cd /path/to/your/app
      #     git pull origin main
      #     npm install
      #     npm run start
      #     EOF
