name: Build API

on:
  pull_request:

# on:
#   push:
#     branches:
#       - main # Adjust to your main branch name
#   pull_request:
#     branches:
#       - main # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Or your preferred Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Prisma Migrate Deploy
        env:
          DATABASE_URL: 'mysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@127.0.0.1:3306/workout_tracker'
        working-directory: apps/api-structure
        run: |
          npx prisma migrate deploy
          npx prisma generate

      - name: Build all packages
        run: npm run build

      - name: Bundle Projects
        run: |
          mkdir -p dist-bundle/api-structure
          mkdir -p dist-bundle/api-tracking
          mkdir -p dist-bundle/web
          cp -r apps/api-structure/dist/* dist-bundle/api-structure/
          cp -r apps/api-tracking/dist/* dist-bundle/api-tracking/
          cp -r apps/web/.next dist-bundle/web/.next
          cp -r apps/web/public dist-bundle/web/public
          zip -r deployment-bundle.zip dist-bundle

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::202533509084:role/GitHubS3
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp deployment-bundle.zip s3://${{ secrets.S3_BUCKET_NAME }}/deployment-bundle.zip
